development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: postgres://uettfpwjhbwpyg:FJq17bbFoSjDgUhxOKP1XWUVw0@ec2-23-21-215-184.compute-1.amazonaws.com:5432/doohv9e3a585
  pool: 5